from typing import Protocol

from app.schemas.coord import Coord


class IMatchEngine(Protocol):
    """Contrato que el motor de partido debe cumplir para que este modulo
    pueda ejecutar comportamientos sobre el.

    Ninguna implementacion de este protocolo deberia exponerle al jugador
    mas que esto. JugadorAPI nunca recibe el motor "crudo": todo pasa por
    estos metodos, siempre acotados a un jugador_id puntual, nunca al
    partido/club completo.
    """

    # --- Consultas (solo lectura) ---
    def pos_pelota(self) -> Coord: ...
    def jugador_aliado_mas_cercano(self, jugador_id: str) -> Coord: ...
    def jugador_enemigo_mas_cercano(self, jugador_id: str) -> Coord: ...
    def arco_aliado(self, jugador_id: str) -> Coord: ...
    def arco_enemigo(self, jugador_id: str) -> Coord: ...
    def pos_jugador(self, jugador_id: str) -> Coord: ...
    def tiene_pelota(self, jugador_id: str) -> bool: ...
    def club_tiene_pelota(self, jugador_id: str) -> bool: ...

    # --- Validaciones de precondicion ---
    def dentro_de_cancha(self, coord: Coord) -> bool: ...
    def jugador_en_cancha(self, jugador_id: str) -> bool: ...

    # --- Mutaciones. Se asume que quien las llama ya valido la precondicion ---
    def aplicar_pase(self, jugador_id: str, destino: Coord) -> None: ...
    def aplicar_remate(self, jugador_id: str, destino: Coord) -> None: ...
    def aplicar_movimiento(self, jugador_id: str, destino: Coord) -> None: ...

    # --- Metadata que necesita el executor ---
    def comportamiento_asignado(self, jugador_id: str) -> str: ...
    def registrar_error(self, jugador_id: str, mensaje: str) -> None: ...