from typing import Protocol

from app.schemas.coord import Coord


class IMatchEngine(Protocol):
    """Contrato que el motor de partido debe cumplir para que este modulo
    pueda ejecutar comportamientos sobre el.
    """

    # --- Consultas (solo lectura) ---
    def ball_position(self) -> Coord: ...
    def nearest_teammate_position(self, player_id: str) -> Coord: ...
    def nearest_opponent_position(self, player_id: str) -> Coord: ...
    def own_goal_position(self, player_id: str) -> Coord: ...
    def opponent_goal_position(self, player_id: str) -> Coord: ...
    def player_position(self, player_id: str) -> Coord: ...
    def player_has_ball(self, player_id: str) -> bool: ...
    def team_has_ball(self, player_id: str) -> bool: ...

    # --- Validaciones de precondicion ---
    def is_inside_field(self, position: Coord) -> bool: ...
    def player_is_on_field(self, player_id: str) -> bool: ...

    # --- Mutaciones. Se asume que quien las llama ya valido la precondicion ---
    def apply_pass(self, player_id: str, destination: Coord) -> None: ...
    def apply_shot(self, player_id: str, destination: Coord) -> None: ...
    def apply_movement(self, player_id: str, destination: Coord) -> None: ...

    # --- Metadata que necesita el executor ---
    def assigned_behavior(self, player_id: str) -> str: ...
    def register_error(self, player_id: str, message: str) -> None: ...